config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" } do

  end

 # get 'auth/:provider/callback', to: 'sessions#create'
 # get 'auth/failure', to: redirect('/')
 # get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'home/index'

  get 'persons/profile'

  root 'home#index'

  get 'persons/profile', as: 'user_root'

  resources :tags, only: [:show]

  resources :books do
    collection { post :import}
  end

  resources :books do
    resources :notes do
      collection { post :import}
    end
  end
end

app/models/note.rb
class Note < ApplicationRecord

   has_many :images, as: :imageable, dependent: :destroy

   belongs_to :book

   validates :name, presence: { message: "не может быть пустым" }

   def self.to_csv(options = {})
      CSV.generate(options) do |csv|
         csv << ["id","name","body","book_id"]
         all.each do |note|
            csv << note.attributes.values_at(*["id","name","body","book_id"])
         end
      end
   end

   def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
         note = find_by_id(row["id".to_i]) || new
         note.attributes = row.to_hash.slice(*column_names)
         note.save!
      end
   end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :find_note
  before_filter :authenticate_user!
  before_action :set_book, only: [:index, :show, :create]
  before_action :check_if_admin, only: [:destroy]


  def index
   @notes = @book.notes



=begin

   respond_to do |format|
     format.html
     format.csv { send_data @notes.to_csv }
   end
=end


  end

  def import
    Note.import(params[:file])
    redirect_to book_notes_path, notice: "Note imported."
  end

  def show
=begin
    extention=@note.image.split('.')
     send_file Rails.root.join('public', 'uploads', @note.image),
               :type=>"application/#{extention[1]}", :x_sendfile=>true
=end

    unless @note
      render text: "Page not found", status: 404
    end
  end

  def new
    @note = Note.new
  end


  # /notes POST
  def create
    note_params = params.require(:note).permit!

=begin
    uploaded_io = params[:note][:image]
    File.open(Rails.root.join('public','uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    @note.image = uploaded_io.original_filename
=end

    @note = @book.notes.create(note_params)




    if @note.errors.empty?
      redirect_to book_notes_path # /notes/:id
    else
      render "new"
    end
  end


  def edit



  end


  # /note/1 PUT
  def update

    @note.update_attributes(params.require(:note).permit!)

    if @note.errors.empty?
      redirect_to book_notes_path(@note.book_id, @note)
    else
      render "edit"
    end



  end

  def destroy
    @note.destroy
    redirect_to action: "index"
    #render json: { success: true }
    #render books_path
    ##  ItemsMailer.item_destroyed(@item).deliver
  end


  private
  def find_note
    @note = Note.where(id: params[:id]).first
   # render_404 unless @note
  end


  def set_book
    @book = Book.find(params[:book_id])
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.slim
|&emsp;&emsp;&emsp;&emsp;Имя:&nbsp;
= f.text_field :name
=@note.errors.full_messages.join(', ')
br
|Содержимое:&nbsp;
= f.text_field :body
br
|&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;Теги:&nbsp;
= f.text_field :tags, label: "Теги"
br
= f.file_field :image

app/views/notes/edit.html.slim
h1
  =t("notes.edit.index")
= link_to t("notes.edit.notes"), :back  , class: "btn btn-sm btn-primary"



= simple_form_for([:book, @note]) do |f|
   = render partial: "form", locals: {f: f}


   br
   = f.submit t("notes.edit.submit") , class: "btn btn-sm btn-primary"

app/views/notes/index.html.slim
.page-header
  .btn-group.pull-right
    .btn-toolbar
      = link_to 'На главную', home_index_path, class: "btn btn-sm btn-primary"
      = link_to 'Создать заметку', new_book_note_path, class: "btn btn-sm btn-primary"
      = link_to 'Блокноты', books_path, class: "btn btn-sm btn-primary"
      div
        h4 Download:
        = link_to "CSV", book_notes_path(format: "csv") , class: "btn btn-sm btn-primary"
      div
h1
  =t("notes.index.index")

- if @notes.empty?
  b
    =t("notes.index.empty")
- else
  table.table
    thead
      tr
        th.col-sm-2 =t("notes.index.tablecolumnname")
        th.col-sm-4 =t("notes.index.tablecolumnbody")
        th.col-sm-2 =t("notes.index.tablecolumntags")
        th.col-sm-1
        th.col-sm-1
    tbody
      tr
        - @notes.each do |i|
          tr
            td= link_to i.name, book_note_path(i.book_id , i)
            td= i.body
            td= i.tags
            td= button_to t("notes.index.tablebtnedit"), edit_book_note_path(i.book_id , i, admin: params[:admin]), method: :get , class: "btn btn-sm btn-primary"
            td= button_to t("notes.index.tablebtndelete"), book_note_path(i.book_id , i, admin: params[:admin]), method: :delete, data: { confirm: t("notes.index.confirm")} , class: "btn btn-sm btn-primary"


- if can? :import, Note
  h2 Import
  = form_tag import_books_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Import"

app/views/notes/new.html.haml
%h1 Create new Note
= link_to 'Вернуться к заметкам', :back

= simple_form_for([:book, @note]) do |f|
 = render partial: "form", locals: {f: f}
 %p= f.submit "Создать"

app/views/notes/new.html.slim
h1
  =t("notes.new.index")
= link_to t("notes.new.back"), :back , class: "btn btn-sm btn-primary"
= simple_form_for([:book, @note]) do |f|
 = render partial: "form", locals: {f: f}
 p= f.submit t("notes.new.submit") , class: "btn btn-sm btn-primary"

app/views/notes/show.html.slim
h1
  =t("notes.show.index")

= link_to t("notes.show.home"), :back, class: "btn btn-sm btn-primary"

ul
  li= @note.name
  li= @note.body
  li= @note.tags
  li= @note.image