config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" } do

  end

 # get 'auth/:provider/callback', to: 'sessions#create'
 # get 'auth/failure', to: redirect('/')
 # get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'home/index'

  get 'persons/profile'

  root 'home#index'

  get 'persons/profile', as: 'user_root'

  resources :tags, only: [:show]

  resources :books do
    collection { post :import}
  end

  resources :books do
    resources :notes do
      collection { post :import}
    end
  end
end

app/models/book.rb
require 'csv'

class Book < ApplicationRecord

  validates :name, presence: { message: "не может быть пустым" }

  has_and_belongs_to_many :users

  has_many :notes
  has_many :taggings
  has_many :tags, through: :taggings

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["name","tags"]
      all.each do |book|
        csv << book.attributes.values_at(*["name","tags"])
      end
    end
  end

  def self.import(file, user = nil)
    CSV.foreach(file.path, headers: true) do |row|
      book = find_by(name: row["name".to_s]) || new
      book.attributes = row.to_hash.slice(*column_names)
      book.users << user
      book.save!
    end
  end



  def all_tags
     self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  load_and_authorize_resource :only => [:index, :show]

  before_action :find_book
  before_filter :authenticate_user!
  before_action :check_if_admin, only: [:destroy]

  def index
    if current_user.admin?
      @books = Book.all
    else
      @books = current_user.books
    end

    respond_to do |format|
      format.html
      format.csv { send_data @books.to_csv }
    end

  end


  def import
    Book.import(params[:file], current_user)
    redirect_to books_path, notice: "Book imported."
  end

  def show
    unless @book
      render text: "Page not found", status: 404
    end
  end

  def new
    @book = Book.new
  end

  def create
    book_params = params.require(:book).permit!
    @book = current_user.books.create(book_params)
    if @book.errors.empty?
      redirect_to books_path # /books/:id
    else
      render "new"
    end
  end


  def edit
  end


  # /note/1 PUT
  def update
    @book.update_attributes(params.require(:book).permit!)
    if @book.errors.empty?
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
     redirect_to action: "index"
    #render json: { success: true }
    #render books_path
  ##  ItemsMailer.item_destroyed(@item).deliver
  end


  private
  def find_book
    @book = Book.where(id: params[:id]).first
    # render_404 unless @book
  end



end

app/helpers/books_helper.rb
module BooksHelper




end

app/views/books/_form.html.slim
|Имя:&nbsp;
= f.text_field :name
=@book.errors.full_messages.join(', ')
br
|Теги:&nbsp;
= f.text_field :all_tags
br

app/views/books/_tags.html.slim
/ tags
- tags.each do |tag|
  = link_to tag.name << " ", tag, class: "tag tag-primary"

app/views/books/edit.html.slim
h1
  =t("books.edit.index")
= link_to t("books.edit.books"), books_path , class: "btn btn-sm btn-primary"
= simple_form_for @book do |f|
  = render partial: "form", locals: {f: f}
  p = f.submit t("books.edit.submit"), class: "btn btn-sm btn-primary"

app/views/books/index.html.slim
.page-header
  .btn-group.pull-right
    .btn-toolbar
      = button_to(t("books.index.createbooks"), new_book_path, class: "btn btn-sm btn-primary", method: :get)
      div
        h4 Download:
        = link_to "CSV", books_path(format: "csv") , class: "btn btn-sm btn-primary"
      div

  h1
    =t("books.index.index")

- if @books.empty?
  b
    =t("books.index.empty")
- else
  table.table
    thead
      tr
        th.col-sm-4 =t("books.index.tablecolumnname")
        th.col-sm-2 =t("books.index.tablecolumntags")
        th.col-sm-1
        th.col-sm-1
    tbody
      tr
        - @books.each do |i|
          tr
            td
              = link_to i.name, book_notes_path(i)
            td
              = render partial: "books/tags", locals: { tags: i.tags }
            td
              = button_to t("books.index.tablebtnedit"), edit_book_path(i, admin: params[:admin]), method: :get, class: "btn btn-sm btn-primary"
            td
              = button_to t("books.index.tablebtndelete"), book_path(i, admin: params[:admin]), method: :delete, data: { confirm: t("books.index.confirm")}, class: "btn btn-sm btn-primary"

- if can? :import, Book
  h2 Import
  = form_tag import_books_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Import"

app/views/books/new.html.haml
%h1 Create new NoteBook
= link_to 'Вернуться к блокнотам', books_path

= simple_form_for @book do |f|
 =render partial: "form", locals: {f: f}
 %p= f.submit "Создать"

app/views/books/new.html.slim
h1
  =t("books.new.index")
= link_to t("books.new.back"), books_path, class: "btn btn-sm btn-primary"
= simple_form_for @book do |f|
 =render partial: "form", locals: {f: f}

 p= f.submit t("books.new.submit"), class: "btn btn-sm btn-primary"

app/views/books/show.html.slim
h1
  =t("books.show.index")
ul
  li= @book.name
  li= @book.access
  li= @book.tags.map { |t| t.name }.join(' ')
= link_to t("books.show.back"), books_path, class: "btn btn-sm btn-primary"